### PR TITLE
Fixed cookie issue

### PR DESCRIPTION
**Pull request by ukp1992**
Hi, 

I tried to fix the "no cookie header output #140" issue.
Please merge if there is no problem.
I will also send you an update of the Japanese translation.

Regards.

### CODE REVIEW

**Comment by rowrawer** [comment]
Hi, thanks for the request. I haven't yet decided whether I will reimplement the onBeforeSendHeaders listener. Your changes seem to be modifying the file heavily due to differences in e.g. indentation. I might restore this functionality at some point, but in a different way. Also, your translation commit states "Russian translation" - feel free to make a pull request with just the translation and I'll gladly merge it.

**Comment by ukp1992** [comment]
Hi,
Sorry, I had tested it in the internal file of the_stream_detector-2.10.12.crx and uploaded it as is.
Please see the diff in the following file for what I did to restore the cookie output.
I simply rolled back requestHeaders.
https://github.com/ukp1992/stream-detector/blob/dad1f600543e50e98e4c52f0ac22cf9756888d0a/src/js/background.js
Regards,

**Comment by rowrawer** [comment]
Yes, I know what you mean and what you are requesting. I will do it once I test and check if everything works fine for me. Don't worry.

**Comment by ukp1992** [comment]
Great Thanks!
I look forward to seeing the good work done.

**Comment by ukp1992** [comment]
Thank you very much for your quick response!
I've confirmed that the cookie output is correct.

> I've decided to restore the previous functionality until I find the time to reimplement it in a better way. Everything should be working fine as of v2.10.13.

**Pull request closed without merging**
