### PR TITLE
Make messages in Slovak shorter so they fit

### PR DESCRIPTION
**Pull request by jose1711**

### CODE REVIEW

**Comment by rowrawer** [comment]
Thanks.

**Comment by rowrawer** [comment]
Hi @jose1711, the translation is now becoming out of date and inaccurate due to various changes. Let me know if you're willing to update it, otherwise I might disable it in the future to avoid confusion.

**Comment by jose1711** [comment]
> Hi @jose1711, the translation is now becoming out of date and inaccurate due to various changes. Let me know if you're willing to update it, otherwise I might disable it in the future to avoid confusion.

Hi @rowrawer I would like to update it. Can you please share instructions?

**Comment by rowrawer** [comment]
You can do it the same way you did it last time. E.g. fork the repo, make a new branch, apply updates, make a pull request.

**Pull request merged**
