### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by zec-github**
tell me if you want something changed

### CODE REVIEW

**Comment by rowrawer** [comment]
Looks good, thanks.

**Comment by rowrawer** [comment]
Hi @gitzec, the translation is now becoming out of date and inaccurate due to various changes. Let me know if you're willing to update it, otherwise I might disable it in the future to avoid confusion.

**Comment by gitzec** [comment]
i can do it in 3 weeks. i have limited internet access atm

**Comment by rowrawer** [comment]
Sure, no problem. If any other German speakers wish to contribute, they can do so as well.

**Comment by gitzec** [comment]
i will update it tmrw

-------- Original-Nachricht --------
Am 1. Juli 2022, 10:48, schrieb rowrawer :

**Comment by rowrawer** [comment]
Hi @gitzec, any update on the translation or should I disable it so as to not confuse users with outdated strings?

**Comment by gitzec** [comment]
Hi, sorry for letting you wait. 1st time you caught me on vacation and, after that I forgot it. 🙈 To get a faster comparison I sorted the JSON before comparing it to find the new vars. That's why it seems to have many more changes that it actually has...

Keen to install lates version to see if the translation looks good and does fit into the controls used...

**Comment by gitzec** [comment]
Damn, I just found out that it is Firefox only as it seems. I changed to Opera months ago. :-|

**Comment by rowrawer** [comment]
Does Opera support Chrome extensions? I include crx files with every GitHub release. You could try unpacking it and testing the addon that way.

**Comment by gitzec** [comment]
Opera is based on chromium and even can use extensions for chrome without any hacks. I will give it a try.

**Comment by rowrawer** [comment]
It should be fine then. The only obstacle is that the extension is not signed (not officially released on the Chrome Web Store) so you might need to find a way to load an unpacked extension.

**Pull request merged**
