### PR TITLE
Updated Korean translation (v.2.7.5)

### PR DESCRIPTION
**Pull request by ubless607**

### CODE REVIEW

**Comment by rowrawer** [comment]
Thanks.

**Comment by rowrawer** [comment]
Hi @ubless607, the translation is now becoming out of date and inaccurate due to various changes. Let me know if you're willing to update it, otherwise I might disable it in the future to avoid confusion.

**Comment by rowrawer** [comment]
Nice, thanks.

**Comment by rowrawer** [comment]
Hi again @ubless607, it's been a million years, but I figured I'd check in - should I go ahead and disable the translation?

**Comment by ubless607** [comment]
@rowrawer I'm sorry for keeping you waiting. I will check it out.

**Pull request merged**
