### PR TITLE
Add changes for chrome support

### LINKED ISSUE #9: Support for Chrome
This is really great. I just found it today
Could you please support also for chrome extension?

### PR DESCRIPTION
**Pull request by daviirodrig**
I made two change for this to work on chrome, following the MDN [guide](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension) building a cross-browser extension
- Change API namespace to chrome.* 
- Change the asynchronous event handling to callbacks instead of promises

Resolves #9

### CODE REVIEW

**Comment by rowrawer** [comment]
Have you tested whether it works at all?

**Comment by daviirodrig** [comment]
Oh yes, sorry for not mentioning this in the PR. I tested on chrome and firefox and surprisingly both works well in my tests

I first started doing the porting just for my use but it turned to work so well with not so much changes that I made this pull request.

**Comment by rowrawer** [comment]
Cool, that's quite surprising. If I ever decide to pay the registration fee, at least there won't be much work additional work to be done. Thanks.

**Comment by smaragdus** [comment]
@rowrawer 

Any chance to publish a `CRX` file in the [Releases](https://github.com/rowrawer/stream-detector/releases) page?

**Comment by rowrawer** [comment]
I'll look into it.

**Comment by smaragdus** [comment]
@rowrawer 

Thanks.

**Pull request merged**
