### PR TITLE
update japanese language

### PR DESCRIPTION
**Pull request by ukp1992**
update Japanese language

### CODE REVIEW

**Comment by 54ac** [comment]
Thanks!

**Comment by rrfqi** [comment]
> Thanks!

hello, since I can't find the issues page, I want to report that, the user-defined commands is not working for some commands such as user-agent and referer, when I copy and paste the url it won't grab the %useragent% and %referer%

**Comment by 54ac** [comment]
> > Thanks!
> 
> hello, since I can't find the issues page, I want to report that, the user-defined commands is not working for some commands such as user-agent and referer, when I copy and paste the url it won't grab the %useragent% and %referer%

As stated in the readme, the reason the issues page is not available is because the addon is not in active development anymore, sorry.

**Comment by rrfqi** [comment]
> > > Thanks!
> > 
> > 
> > hello, since I can't find the issues page, I want to report that, the user-defined commands is not working for some commands such as user-agent and referer, when I copy and paste the url it won't grab the %useragent% and %referer%
> 
> As stated in the readme, the reason the issues page is not available is because the addon is not in active development anymore, sorry.

Oh I see, that's kinda sad, anyway thanks for answering

**Pull request merged**
