### PR TITLE
automatically update The Stream Detector chromium

### PR DESCRIPTION
**Pull request by candrapersada**
#### If you are a chrome extension developer...

and do not have your extension listed in the Chrome Web Store, you can still enable updates via chromium-web-store by hosting an [update manifest file](https://developer.chrome.com/apps/autoupdate#update_manifest); see [updates.xml](https://github.com/NeverDecaf/chromium-web-store/blob/master/updates.xml) in this repo for an example. You must also specify a url to access this file in your extension's `manifest.json` under the [`update_url`](https://developer.chrome.com/apps/autoupdate#update_url) field; again, see [manifest.json](https://github.com/NeverDecaf/chromium-web-store/blob/master/src/manifest.json) in this repo for an example.

### CODE REVIEW

**Comment by rowrawer** [comment]
Wouldn't this mess up the autoupdate in Firefox?

**Comment by rowrawer** [comment]
Can you explain what it is exactly that you're trying to accomplish? At this point I'd rather be removing Chrome-related code, not adding more of it.

**Comment by candrapersada** [comment]
automatically update The Stream Detector on chromium

**Comment by rowrawer** [comment]
How do you plan on accounting for the automatic manifest generation in Rollup and differentiating between Firefox and Chrome builds? Again, I'd rather not add any Chrome-related code to the addon as I'm not planning on supporting Chrome much longer, especially with Google transitioning to Manifest V3.

**Pull request closed without merging**
