### PR TITLE
overflow adjustments

### PR DESCRIPTION
**Pull request by ericlee4**
Moved the scrollbar to its own div and aligned the tables in a flex column so the buttons are stuck to the bottom of the popup.

### CODE REVIEW

**Comment by rowrawer** [comment]
Nice, thanks.

**Comment by rowrawer** [comment]
I've been testing this out. Unfortunately the overflow/flex doesn't seem to work properly, at least not on Windows, even with a lengthy list.

**Comment by ericlee4** [comment]
Hmm sorry about that, the changes I made seemed to be pretty in line with the CSS spec. I'm testing with Firefox 85.0.2 on Linux, maybe it's a little different on Windows. I'll try it out, what version are you using?

**Comment by rowrawer** [comment]
I'm using Firefox 85.0.2 on Windows. I also check in 52 ESR for compatibility issues.

**Comment by ericlee4** [comment]
I'm looking at the code now, the issue is due to the change that you made immediately after to remove the default browser style. https://github.com/rowrawer/stream-detector/commit/5ab79530ac85a26226fb715520d1d134ff5c2359#diff-ffa5b716b5a57837f7929dfcca4b4dfdeb97210a7fd5a12d2f1978846d6f1743L24

Was there any particular issue you were trying to fix that needed to remove the `browser_style`? If it's not trivial to add it back and fix the issues then I can fix the table with some extra CSS.

**Comment by ericlee4** [comment]
This patch is enough to fix the problems on master with the list of URLs being too small and the columns being equal width but the font size is just related to the `browser_style` property. 

```
diff --git a/content/popup.html b/content/popup.html
index da6d526..c0651ac 100644
--- a/content/popup.html
+++ b/content/popup.html
@@ -7,6 +7,7 @@
 			/* might use a css file in the future. no need for now */
 			html,
 			body {
+				display: flex;
 				padding: 0;
 				margin: 0;
 				width: 100%;
@@ -24,6 +25,7 @@
 				display: flex;
 				flex-direction: column;
 				height: 100%;
+        width: 100%;
 			}
 
 			.url-list {
@@ -31,7 +33,6 @@
 			}
 
 			table {
-				table-layout: fixed;
 				border-collapse: collapse;
 				width: 100%;
 			}
```

**Comment by rowrawer** [comment]
Thanks. I removed it because it seemed to be redundant at the time (shows what I know) and I didn't want it to interfere with the Chrome builds I was testing out. I'll add it back in. After applying your patch and reverting `browser_style` back to true everything seems fine, but extremely long words overflow the table in width:

**Comment by ericlee4** [comment]
My second patch isn't needed with `"browser_style": true` but there's still the issue of the `x` and `Type` columns being too large for their content. If you don't want to use the browser styles (no idea what the implications are for chrome) then the easiest solution is probably to use `table-layout: fixed` and give the columns a width.

```
diff --git a/content/popup.html b/content/popup.html
index da6d526..bfe5b61 100644
--- a/content/popup.html
+++ b/content/popup.html
@@ -7,6 +7,7 @@
 			/* might use a css file in the future. no need for now */
 			html,
 			body {
+				display: flex;
 				padding: 0;
 				margin: 0;
 				width: 100%;
@@ -30,6 +31,10 @@
 				overflow: auto;
 			}
 
+			.url-column-shrink {
+				width: 4em;
+			}
+
 			table {
 				table-layout: fixed;
 				border-collapse: collapse;
@@ -139,11 +144,11 @@
 			<table>
 				<thead>
 				<tr>
-					<th><label for="popupType"></label></th>
+					<th class="url-column-shrink"><label for="popupType"></label></th>
 					<th><label for="popupFilename"></label></th>
 					<th><label for="popupSource"></label></th>
 					<th><label for="popupTimestamp"></label></th>
-					<th>✖</th>
+					<th class="url-column-shrink">✖</th>
 				</tr>
 				</thead>
 				<tbody id="popupUrlList"></tbody>

```

Alternatively it could be calculated in JS or rewritten with a flex layout.

**Comment by rowrawer** [comment]
Yeah that's what I was thinking also. Thanks for the suggestions.

**Pull request merged**
